`Resolver` compiles to a class that early JDK 8 versions cannot load
The fix for #434 introduced a bug that broke old versions of JDK 8
(8u341 and earlier).  It moved the lambda that gives `FromResolver`
its `FromBuilder` out of a field initializer and into the arguments of
the constructor's `this(...)` call.  The lambda reads fields of the
enclosing `Resolver`, which results in field names that contain dots:

    java.lang.ClassFormatError: Illegal field name
    "net.hydromatic.morel.compile.Resolver$this" in class
    net/hydromatic/morel/compile/Resolver$FromResolver